## Write a Pandas program to filter all records starting from the 2nd row, access every 5th row from world alcohol consumption dataset.

In [1]:
import pandas as pd

In [2]:
def filter_rows():
    df = pd.read_csv('world_alcohol.csv')
    
    return df.iloc[1::5].head(10)

In [3]:
filter_rows()

,Year,WHO region,Country,Beverage Types,Display Value
1,1986,Americas,Uruguay,Other,0.50
6,1987,Africa,Mauritius,Wine,0.13
11,1989,Americas,Guatemala,Beer,0.62
16,1984,Americas,Costa Rica,Wine,0.06
21,1989,Americas,Costa Rica,Spirits,4.51
26,1985,Europe,United Kingdom of Great Britain and Northern I...,Wine,1.36
31,1986,Western Pacific,Micronesia (Federated States of),Wine,0.00
36,1987,Eastern Mediterranean,Egypt,Beer,0.07
41,1986,Europe,Czech Republic,Beer,6.82
46,1987,Americas,Trinidad and Tobago,Spirits,2.26